# Streamlit secrets configuration
# This file is for local development only
# DO NOT commit this file to Git (it should be in .gitignore)

PAML_API_KEY = "AIzaSyCHQdqte9be5P3avU19YQGeoQ517Ttf4IM"

# For production deployment, add secrets through Streamlit Cloud interface
# Use the same format: PAML_API_KEY = "your_actual_key"